apiVersion: v1
kind: Service
metadata:
  name: {{ include "stubby.fullname" . }}
  labels: {{- include "stubby.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "stubby.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
